Repository codesquad-member-2020/sidedish-07, pull requests merged in 2020-04, with the labels that each got.

#5 [#2] Chore: 루트 디렉토리 idea 폴더 제거
  .idea/$CACHE_FILE$
  .idea/.gitignore
  .idea/dictionaries
  .idea/misc.xml
  .idea/modules.xml
  .idea/sidedish-07.iml
  .idea/vcs.xml
Labels: BE

#11 [#3] 메인화면 UI 구현
  iOS/.gitignore
  iOS/SideDish/SideDish.xcodeproj/project.pbxproj
  iOS/SideDish/SideDish.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/SideDish/SideDish.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/SideDish/SideDish/AppDelegate.swift
  iOS/SideDish/SideDish/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/sample.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/sample.imageset/sample.jpg
  iOS/SideDish/SideDish/Base.lproj/LaunchScreen.storyboard
  iOS/SideDish/SideDish/Base.lproj/Main.storyboard
  iOS/SideDish/SideDish/Info.plist
  iOS/SideDish/SideDish/MainScene/View/KeywordLabel.swift
  iOS/SideDish/SideDish/MainScene/View/MenuSectionHeader.swift
  iOS/SideDish/SideDish/MainScene/View/MenuTableViewCell.swift
  iOS/SideDish/SideDish/MainScene/ViewController.swift
  iOS/SideDish/SideDish/SceneDelegate.swift
Labels: iOS

#15 [FE] 개발환경 구축
  FE/sidedish/.env
  FE/sidedish/.gitignore
  FE/sidedish/README.md
  FE/sidedish/package-lock.json
  FE/sidedish/package.json
  FE/sidedish/src/App.js
  FE/sidedish/src/App.test.js
  FE/sidedish/src/index.js
  FE/sidedish/src/serviceWorker.js
  FE/sidedish/src/setupTests.js
Labels: FE

#16 [#12] 상세페이지 UI 구현
  iOS/SideDish/SideDish.xcodeproj/project.pbxproj
  iOS/SideDish/SideDish/Assets.xcassets/detail1.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/detail1.imageset/detail1.jpg
  iOS/SideDish/SideDish/Assets.xcassets/detail10.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/detail10.imageset/detail10.jpg
  iOS/SideDish/SideDish/Assets.xcassets/detail2.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/detail2.imageset/detail2.jpg
  iOS/SideDish/SideDish/Assets.xcassets/detail3.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/detail3.imageset/detail3.jpg
  iOS/SideDish/SideDish/Assets.xcassets/detail4.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/detail4.imageset/detail4.jpg
  iOS/SideDish/SideDish/Assets.xcassets/detail5.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/detail5.imageset/detail5.jpg
  iOS/SideDish/SideDish/Assets.xcassets/detail6.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/detail6.imageset/detail6.jpg
  iOS/SideDish/SideDish/Assets.xcassets/detail7.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/detail7.imageset/detail7.jpg
  iOS/SideDish/SideDish/Assets.xcassets/detail8.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/detail8.imageset/detail8.jpg
  iOS/SideDish/SideDish/Assets.xcassets/detail9.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/detail9.imageset/detail9.jpg
  iOS/SideDish/SideDish/Assets.xcassets/scroll1.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/scroll1.imageset/scroll1.jpg
  iOS/SideDish/SideDish/Assets.xcassets/scroll2.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/scroll2.imageset/scroll2.jpg
  iOS/SideDish/SideDish/Assets.xcassets/scroll3.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/scroll3.imageset/scroll3.jpg
  iOS/SideDish/SideDish/Assets.xcassets/scroll4.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/scroll4.imageset/scroll4.jpg
  iOS/SideDish/SideDish/Base.lproj/Main.storyboard
  iOS/SideDish/SideDish/DescriptionScene/DescriptionViewController.swift
  iOS/SideDish/SideDish/MainScene/ViewController.swift
Labels: iOS

#19 [#14] 컴포넌트별 스켈레톤 코드 작성
  FE/sidedish/.gitignore
  FE/sidedish/public/favicon.ico
  FE/sidedish/public/index.html
  FE/sidedish/public/logo192.png
  FE/sidedish/public/logo512.png
  FE/sidedish/public/manifest.json
  FE/sidedish/public/robots.txt
  FE/sidedish/src/App.js
  FE/sidedish/src/components/Carousel/Carousel.jsx
  FE/sidedish/src/components/Header/Header.jsx
  FE/sidedish/src/components/Menu/Menu.jsx
Labels: FE

#22 [#20] Header 영역 정적 UI 구현
  FE/sidedish/src/App.js
  FE/sidedish/src/components/Header/Header.jsx
  FE/sidedish/src/components/Navigation/Navigation.jsx
Labels: FE

#24 [#21] Navigation UI 정적으로 구현
  FE/sidedish/src/App.js
  FE/sidedish/src/components/Header/Header.jsx
  FE/sidedish/src/components/Navigation/Navigation.jsx
Labels: FE

#29 [#13] OAuth2 기능 구현
  BE/src/main/java/com/codesquad/sidedish/api/LoginController.java
  BE/src/main/java/com/codesquad/sidedish/entity/OAuthGithubToken.java
  BE/src/main/java/com/codesquad/sidedish/service/OAuthService.java
  BE/src/main/resources/static/index.html
Labels: BE, feature

#37 [#36] Access-Control-Allow-Origin 헤더 관련 Cors 설정
  BE/src/main/java/com/codesquad/sidedish/config/CorsConfig.java
Labels: BE, bug

#40 첫번째 화면 API 통신 구현
  iOS/SideDish/SideDish.xcodeproj/project.pbxproj
  iOS/SideDish/SideDish/Base.lproj/Main.storyboard
  iOS/SideDish/SideDish/DescriptionScene/DescriptionViewController.swift
  iOS/SideDish/SideDish/Info.plist
  iOS/SideDish/SideDish/MainScene/MenuTableViewDataSource.swift
  iOS/SideDish/SideDish/MainScene/View/KeywordLabel.swift
  iOS/SideDish/SideDish/MainScene/View/MenuTableViewCell.swift
  iOS/SideDish/SideDish/MainScene/View/PriceLabel.swift
  iOS/SideDish/SideDish/MainScene/ViewController.swift
  iOS/SideDish/SideDish/Model/DataManager.swift
  iOS/SideDish/SideDish/Model/NetworkManager.swift
  iOS/SideDish/SideDish/Model/SideDish.swift
  iOS/SideDish/SideDish/Model/SideDishUseCase.swift
Labels: iOS

#43 이미지 캐싱, 피드백 반영
  iOS/SideDish/SideDish.xcodeproj/project.pbxproj
  iOS/SideDish/SideDish/MainScene/MenuTableViewDataSource.swift
  iOS/SideDish/SideDish/MainScene/View/KeywordLabel.swift
  iOS/SideDish/SideDish/MainScene/View/MenuTableViewCell.swift
  iOS/SideDish/SideDish/MainScene/ViewController.swift
  iOS/SideDish/SideDish/Model/DataManager.swift
  iOS/SideDish/SideDish/Model/ImageFileManager.swift
  iOS/SideDish/SideDish/Model/SideDishUseCase.swift
Labels: iOS

#50 [#49] 부트 실행 시 DB 초기화 작업 제거
  BE/src/main/java/com/codesquad/sidedish/initialization/SidedishApplicationRunner.java
  BE/src/main/resources/application-master.properties
  BE/src/main/resources/application.properties
  BE/src/main/resources/static/index.html
Labels: BE

#51 [Deploy] 부트 실행 시 DB 데이터 초기화 작업 제거
  BE/src/main/java/com/codesquad/sidedish/initialization/SidedishApplicationRunner.java
  BE/src/main/resources/application.properties
Labels: BE, deploy

#56 [#52] 외장 톰캣을 이용하여 war 배포
  BE/src/main/java/com/codesquad/sidedish/SidedishApplication.java
  BE/src/main/java/com/codesquad/sidedish/initialization/SidedishWebInitializer.java
Labels: BE

#57 [Deploy] war 파일로 빌드, 외장 톰캣으로 배포
  BE/src/main/java/com/codesquad/sidedish/SidedishApplication.java
  BE/src/main/java/com/codesquad/sidedish/initialization/SidedishWebInitializer.java
Labels: BE, deploy

#54 [#25] 메인화면 반찬별 캐러셀 구현
  FE/sidedish/src/App.js
  FE/sidedish/src/components/Carousel/Arrow.jsx
  FE/sidedish/src/components/Carousel/Carousel.jsx
  FE/sidedish/src/components/Carousel/CarouselItem.jsx
  FE/sidedish/src/components/Header/Header.jsx
  FE/sidedish/src/components/Navigation/Navigation.jsx
Labels: FE, feature

#66 [#55] 상세페이지 구현
  FE/sidedish/public/favicon.ico
  FE/sidedish/public/index.html
  FE/sidedish/public/logo192.png
  FE/sidedish/public/logo512.png
  FE/sidedish/public/robots.txt
  FE/sidedish/src/App.js
  FE/sidedish/src/components/Carousel/Arrow.jsx
  FE/sidedish/src/components/Carousel/Carousel.jsx
  FE/sidedish/src/components/Carousel/CarouselItem.jsx
  FE/sidedish/src/components/Carousel/ProductDetail/Modal.jsx
  FE/sidedish/src/util/util.js
Labels: FE, feature

#69 Fix : hash 데이터 전달 실패 문제 해결
  FE/sidedish/src/App.js
  FE/sidedish/src/components/Carousel/Carousel.jsx
  FE/sidedish/src/components/Carousel/CarouselItem.jsx
  FE/sidedish/src/components/Carousel/ProductDetail/Modal.jsx
Labels: FE

#70 Feat : 상세페이지 세일가격 표시 기능 추가
  FE/sidedish/src/components/Carousel/ProductDetail/Modal.jsx
Labels: FE

#71 로그인 API 통신, 상세페이지 구현
  iOS/SideDish/SideDish.xcodeproj/project.pbxproj
  iOS/SideDish/SideDish/Assets.xcassets/GitHub-Mark.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/GitHub-Mark.imageset/GitHub-Mark-Light-120px-plus.png
  iOS/SideDish/SideDish/Assets.xcassets/background.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/background.imageset/background.png
  iOS/SideDish/SideDish/Base.lproj/Main.storyboard
  iOS/SideDish/SideDish/DescriptionScene/DescriptionViewController.swift
  iOS/SideDish/SideDish/DescriptionScene/View/DetailStackView.swift
  iOS/SideDish/SideDish/DescriptionScene/View/PreviewScrollView.swift
  iOS/SideDish/SideDish/Extension/DateCurrentDate.swift
  iOS/SideDish/SideDish/Extension/StringRegex.swift
  iOS/SideDish/SideDish/Extension/UIViewControllerShortDelayAlert.swift
  iOS/SideDish/SideDish/Extension/WKWebViewCookies.swift
  iOS/SideDish/SideDish/Login/LoginButton.swift
  iOS/SideDish/SideDish/Login/LoginViewController.swift
  iOS/SideDish/SideDish/Login/WebViewController.swift
  iOS/SideDish/SideDish/MainScene/MainViewController.swift
  iOS/SideDish/SideDish/MainScene/MenuTableViewDataSource.swift
  iOS/SideDish/SideDish/MainScene/View/BadgeStackView.swift
  iOS/SideDish/SideDish/MainScene/View/LogInOutButton.swift
  iOS/SideDish/SideDish/MainScene/View/MenuTableViewCell.swift
  iOS/SideDish/SideDish/Model/ImageFileManager.swift
  iOS/SideDish/SideDish/Model/NetworkManager.swift
  iOS/SideDish/SideDish/Model/SideDish.swift
  iOS/SideDish/SideDish/Model/SideDishUseCase.swift
Labels: iOS

#73 [#72] 쿠키 패스 지정
  BE/src/main/java/com/codesquad/sidedish/api/LoginController.java
Labels: BE, bug

#74 [Deploy] 리다이렉트 시 쿠키가 유지되지 않는 문제 해결 배포
  BE/src/main/java/com/codesquad/sidedish/api/LoginController.java
  FE/sidedish/public/favicon.ico
  FE/sidedish/public/index.html
  FE/sidedish/public/logo192.png
  FE/sidedish/public/logo512.png
  FE/sidedish/public/robots.txt
  FE/sidedish/src/App.js
  FE/sidedish/src/components/Carousel/Arrow.jsx
  FE/sidedish/src/components/Carousel/Carousel.jsx
  FE/sidedish/src/components/Carousel/CarouselItem.jsx
  FE/sidedish/src/components/Carousel/ProductDetail/Modal.jsx
  FE/sidedish/src/util/util.js
  iOS/SideDish/SideDish.xcodeproj/project.pbxproj
  iOS/SideDish/SideDish/Assets.xcassets/GitHub-Mark.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/GitHub-Mark.imageset/GitHub-Mark-Light-120px-plus.png
  iOS/SideDish/SideDish/Assets.xcassets/background.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/background.imageset/background.png
  iOS/SideDish/SideDish/Base.lproj/Main.storyboard
  iOS/SideDish/SideDish/DescriptionScene/DescriptionViewController.swift
  iOS/SideDish/SideDish/DescriptionScene/View/DetailStackView.swift
  iOS/SideDish/SideDish/DescriptionScene/View/PreviewScrollView.swift
  iOS/SideDish/SideDish/Extension/DateCurrentDate.swift
  iOS/SideDish/SideDish/Extension/StringRegex.swift
  iOS/SideDish/SideDish/Extension/UIViewControllerShortDelayAlert.swift
  iOS/SideDish/SideDish/Extension/WKWebViewCookies.swift
  iOS/SideDish/SideDish/Login/LoginButton.swift
  iOS/SideDish/SideDish/Login/LoginViewController.swift
  iOS/SideDish/SideDish/Login/WebViewController.swift
  iOS/SideDish/SideDish/MainScene/MainViewController.swift
  iOS/SideDish/SideDish/MainScene/MenuTableViewDataSource.swift
  iOS/SideDish/SideDish/MainScene/View/BadgeStackView.swift
  iOS/SideDish/SideDish/MainScene/View/LogInOutButton.swift
  iOS/SideDish/SideDish/MainScene/View/MenuTableViewCell.swift
  iOS/SideDish/SideDish/Model/ImageFileManager.swift
  iOS/SideDish/SideDish/Model/NetworkManager.swift
  iOS/SideDish/SideDish/Model/SideDish.swift
  iOS/SideDish/SideDish/Model/SideDishUseCase.swift
Labels: BE, bug, deploy
